version: "3.5"
#To rebuild images you must use `docker-compose build` or `docker-compose up --build`
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
